services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        user: sammy
        uid: 1000
    image: dawapp
    container_name: dawapp-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - db
    networks:
      - dawapp

  db:
    image: mysql:5.7
    container_name: dawapp-db
    restart: unless-stopped
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: entrenamientos
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - dawapp

  nginx:
    image: nginx:1.17-alpine
    container_name: dawapp-nginx
    restart: unless-stopped
    platform: linux/amd64
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - dawapp

networks:
  dawapp:
    driver: bridge
